project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning Blog"
  repo-url: https://github.com/iambarat/ml_blog/tree/main/posts
  repo-actions: [source]
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/iambarat
      - icon: twitter
        href: https://twitter.com/iambota_
  
format:
  html:
    theme: solar
    css: styles.css
editor: visual

